/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 -T mats.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/mats-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mat1.geometry} material={materials.mat1} position={[0, 0, -8.83]} />
      <mesh geometry={nodes.mat.geometry} material={materials.mat2} position={[3.61, 0, -8.83]} />
      <mesh geometry={nodes.mat3.geometry} material={materials.mat3} position={[8.25, 0, -8.83]} />
      <mesh geometry={nodes.mat4.geometry} material={materials.mat4} position={[12.86, 0, -8.83]} />
      <mesh geometry={nodes.mat5.geometry} material={materials.mat5} position={[18.21, 0, -8.83]} />
      <mesh geometry={nodes.wall.geometry} material={materials.wall} position={[17.74, 0, -2.29]} />
      <mesh geometry={nodes.ground.geometry} material={materials.ground} position={[1.22, -0.39, -2.26]} />
      <mesh geometry={nodes.water.geometry} material={materials.water} position={[3.89, -0.32, -2.3]} />
      <mesh geometry={nodes.grass.geometry} material={materials.moss} position={[6.51, -0.28, -2.32]} />
      <mesh geometry={nodes.pavement.geometry} material={materials.pavement} position={[9.58, -0.28, -2.28]} />
      <mesh geometry={nodes.asphalt.geometry} material={materials.asphalt} position={[12.78, -0.28, -2.21]} />
    </group>
  )
}

useGLTF.preload('/mats-transformed.glb')
