/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 -T portal_gun.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/portal_gun-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_0.geometry} material={materials.material} />
      <mesh geometry={nodes.Object_0_1.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_0_2.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_0_3.geometry} material={materials.material_3} />
      <mesh geometry={nodes.Object_0_4.geometry} material={materials.material_4} />
      <mesh geometry={nodes.Object_0_5.geometry} material={materials.material_5} />
      <mesh geometry={nodes.Object_0_6.geometry} material={materials.material_6} />
      <mesh geometry={nodes.Object_0_7.geometry} material={materials.material_7} />
    </group>
  )
}

useGLTF.preload('/portal_gun-transformed.glb')
